<?php

/**
 * Implements hook_theme().
 */
function event_order_schedule_theme($existing, $type, $theme, $path) {
  return [
    'event_order_schedule' => [
      'variables' => [
        'state' => NULL,
        'event_start' => NULL,
        'event_end' => NULL,
        'event_duration' => NULL,
        'regular_start' => NULL,
        'preorder_start' => NULL,
        'preorder_price' => NULL,
        'regular_price' => NULL,
        'button' => NULL,
        'cta' => NULL,
      ],
      'template' => 'event-order-schedule',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function event_order_schedule_cron() {
  \Drupal::service('event_order_schedule.manager')
    ->synchronize();
}