<?php

/**
 * Implements hook_preprocess_views_view_list().
 */

function custom_view_preprocess_views_view_list(
  array &$variables
): void {
  $swipe_enabled = [
    'amenities',
    'event',
    'hotel',
  ];

  $variables['content_type'] = FALSE;

  $view = $variables['view'];
  $display_plugin = $view->display_handler->getPluginId();

  foreach ($view->result as $result) {
    if (
      !empty($result->_entity) &&
      $result->_entity->getEntityTypeId() === 'node' &&
      $display_plugin === 'block'
    ) {
      $content_type = $result->_entity->bundle();

      if (in_array($content_type, $swipe_enabled, TRUE)) {
        $variables['is_block'] = TRUE;
        if($content_type === 'event'){
           $variables['is_teaser'] = TRUE;
        }
      }

      break;
    }
  }
}

/**
 * Implements hook_preprocess_block().
 */

function custom_view_preprocess_block(array &$variables) {
  $path = \Drupal::service('path.current')->getPath();
  $parts = explode('/', trim($path, '/'));
  $variables['node_title'] = '';
  $variables['show_menu'] = TRUE;

  if ($variables['plugin_id'] !== 'page_title_block') {
    $variables['show_menu'] = FALSE;
    return;
  }

  if (count($parts) === 2) {
    $slug = $parts[1];

    $nodes = \Drupal::entityTypeManager()
      ->getStorage('node')
      ->loadByProperties(['field_slug' => $slug]);

    $node = reset($nodes);

    if ($node instanceof \Drupal\node\NodeInterface) {
      $variables['node_title'] = $node->getTitle();
    }
  }
}